### ISSUE TITLE
Design an initial home screen for the app

### ISSUE THREAD

**Issue by JayBeavers** [MSREnable/EyeCatcher#27]
Emily & Yutha

**Comment by peteams** [comment]
[EYECATCHER WELCOME PAGE #3.pdf](https://github.com/MSREnable/EyeCatcher/files/5549751/EYECATCHER.WELCOME.PAGE.3.pdf)
[EYECATCHER WELCOME PAGE #1.pdf](https://github.com/MSREnable/EyeCatcher/files/5549753/EYECATCHER.WELCOME.PAGE.1.pdf)
