### ISSUE TITLE
Data transfer exit screen- Misleading wording

### ISSUE THREAD

**Issue by ekornm** [MSREnable/EyeCatcher#9]
Wording states "images will continue to be sent even once you exit". Changes could encourage user to keep app open while the images download.

**Comment by joncamp** [comment]
this seems to be fixed:
![image](https://user-images.githubusercontent.com/11506084/98043198-b105fb00-1dd9-11eb-9112-7c18f42fe50e.png)

**Comment by JayBeavers** [comment]
Going to call this one fixed in 2012.0.0
